# ==============================================================================
# ARGO CD
# AWS ALB Ingress Configuration
# ==============================================================================

configs:
  params:
    server.insecure: true

server:
  ingress:
    enabled: true
    ingressClassName: alb

    hostname: argocd-retail-v2.tinacloud.dev

    annotations:
      external-dns.alpha.kubernetes.io/hostname: argocd-retail-v2.tinacloud.dev

      alb.ingress.kubernetes.io/scheme: internet-facing

      alb.ingress.kubernetes.io/target-type: ip

      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'

      alb.ingress.kubernetes.io/ssl-redirect: "443"

      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:162663626265:certificate/a4eb55e2-32e6-4241-8775-262a19640c13

      alb.ingress.kubernetes.io/backend-protocol: HTTP

      alb.ingress.kubernetes.io/healthcheck-path: /healthz

      alb.ingress.kubernetes.io/success-codes: "200"
